import { Product, Review } from './types';

// Unsplash high-quality menswear image assets curated for a luxury linen brand
const shirtImages = {
  white: [
    'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800&auto=format&fit=crop&q=80'
  ],
  natural: [
    'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&auto=format&fit=crop&q=80'
  ],
  olive: [
    'https://images.unsplash.com/photo-1541101767792-f9b2b1c4f127?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1505022610485-0249ba5b3675?w=800&auto=format&fit=crop&q=80'
  ],
  terracotta: [
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=800&auto=format&fit=crop&q=80'
  ]
};

const pantImages = {
  natural: [
    'https://images.unsplash.com/photo-1505022610485-0249ba5b3675?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800&auto=format&fit=crop&q=80'
  ],
  dark: [
    'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800&auto=format&fit=crop&q=80'
  ],
  light: [
    'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1516257984-b1b4d707412e?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1562157873-818bc0726f68?w=800&auto=format&fit=crop&q=80',
    'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&auto=format&fit=crop&q=80'
  ]
};

export const COLOR_SWATCHES = [
  { name: 'Linen White', hex: '#F5F1E8' },
  { name: 'Natural Sand', hex: '#E4D8C3' },
  { name: 'Warm Beige', hex: '#C9B79C' },
  { name: 'Terracotta Rust', hex: '#B85C38' },
  { name: 'Olive Green', hex: '#5C6B4A' },
  { name: 'Ink Navy', hex: '#16202A' },
  { name: 'Charcoal', hex: '#1F1B16' },
  { name: 'Sage Grey', hex: '#8C9C8F' },
  { name: 'Sky Blue', hex: '#A4C3D2' },
  { name: 'Desert Rose', hex: '#C58B82' }
];

const SHIRT_SIZES = ['S', 'M', 'L', 'XL', 'XXL', '3XL'];
const PANTS_SIZES = ['30', '32', '34', '36', '38'];

export let products: Product[] = [
  // ==================== LINEN SHIRTS (10 products) ====================
  {
    id: 'ls-1',
    name: 'Amalfi Pure Linen Shirt',
    slug: 'amalfi-pure-linen-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3499,
    compareAtPrice: 4999,
    fabric: '100% Pure Linen',
    fit: 'Regular',
    color: 'Linen White',
    colorHex: '#F5F1E8',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.white,
    rating: 4.8,
    reviewCount: 124,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-03-12',
    description: 'Woven from premium European flax, our Amalfi shirt offers unparalleled breathability and classic structure. Finished with premium mother-of-pearl buttons and a neat spread collar.',
    details: ['100% Belgian Flax Linen', 'Moisture-wicking & highly breathable', 'Tailored fit with extra shoulder room', 'Pre-washed for signature softness'],
    careInstructions: ['Dry clean recommended or gentle hand wash', 'Do not tumble dry', 'Iron while damp for crisp finish']
  },
  {
    id: 'ls-2',
    name: 'Goa Mandarin Collar Shirt',
    slug: 'goa-mandarin-collar-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'half-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3199,
    compareAtPrice: 4599,
    fabric: '100% Pure Linen',
    fit: 'Relaxed',
    color: 'Natural Sand',
    colorHex: '#E4D8C3',
    sizes: SHIRT_SIZES,
    collar: 'Mandarin',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.natural,
    rating: 4.6,
    reviewCount: 98,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-04-10',
    description: 'Embrace warm evenings with our Mandarin Collar Linen Shirt. Features a relaxed half-sleeve silhouette, curved hem, and a refined band collar for an effortless smart-casual look.',
    details: ['100% French Flax Linen', 'Comfortable relaxed fit', 'Short-sleeve style', 'Minimalist chest pocket'],
    careInstructions: ['Machine wash cold on gentle cycle', 'Hang dry in shade', 'Warm iron if needed']
  },
  {
    id: 'ls-3',
    name: 'Terracotta Classic Linen Shirt',
    slug: 'terracotta-classic-linen-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3699,
    compareAtPrice: 4999,
    fabric: '100% Pure Linen',
    fit: 'Slim',
    color: 'Terracotta Rust',
    colorHex: '#B85C38',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.terracotta,
    rating: 4.9,
    reviewCount: 43,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-02',
    description: 'Dyed in a rich earth-toned Terracotta, this slim-fit pure linen shirt adds structural definition to summer tailoring. Pairs perfectly with light trousers.',
    details: ['100% Pure Irish Linen', 'Hand-dyed organic colorway', 'Slim athletic fit', 'Double yoke back for comfort'],
    careInstructions: ['Hand wash separately first', 'Do not bleach', 'Iron on reverse side']
  },
  {
    id: 'ls-4',
    name: 'Sage Meadow Linen Stripe Shirt',
    slug: 'sage-meadow-linen-stripe-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3799,
    compareAtPrice: 5299,
    fabric: '100% Pure Linen',
    fit: 'Regular',
    color: 'Sage Grey',
    colorHex: '#8C9C8F',
    sizes: SHIRT_SIZES,
    collar: 'Cutaway',
    sleeve: 'Full Sleeve',
    pattern: 'Striped',
    images: shirtImages.olive,
    rating: 4.5,
    reviewCount: 31,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-10',
    description: 'A delicate vertical awning stripe in calming Sage Grey. Crafted with a premium cutaway collar that stands tall with or without a blazer.',
    details: ['Premium organic European linen', 'Classic vertical stripe pattern', 'Modern cutaway collar with collar stays', 'Adjustable mitered cuffs'],
    careInstructions: ['Wash inside out on gentle cycle', 'Steam iron for premium texture']
  },
  {
    id: 'ls-5',
    name: 'Kashmir Summer Mandarin Shirt',
    slug: 'kashmir-summer-mandarin-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3299,
    compareAtPrice: 4299,
    fabric: '100% Pure Linen',
    fit: 'Regular',
    color: 'Sky Blue',
    colorHex: '#A4C3D2',
    sizes: SHIRT_SIZES,
    collar: 'Mandarin',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.white,
    rating: 4.7,
    reviewCount: 74,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-02-18',
    description: 'A lightweight sky-colored linen shirt featuring a subtle slub texture. Equipped with an elegant band collar that maintains crisp posture.',
    details: ['100% Premium linen', 'Sky blue linen shade', 'Pre-shrunk and garment dyed', 'Mandarin band collar style'],
    careInstructions: ['Wash with like colors', 'Line dry recommended']
  },
  {
    id: 'ls-6',
    name: 'Rajasthan Dusk Linen Shirt',
    slug: 'rajasthan-dusk-linen-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3599,
    compareAtPrice: 4999,
    fabric: '100% Pure Linen',
    fit: 'Relaxed',
    color: 'Ink Navy',
    colorHex: '#16202A',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.natural,
    rating: 4.8,
    reviewCount: 88,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-03-01',
    description: 'Our signature dark indigo hue on premium European flax. This shirt works beautifully as an overshirt or buttoned up for formal resort dinners.',
    details: ['Indigo dyed pure linen', 'Heavyweight flax texture for beautiful drape', 'Button-up barrel cuffs', 'Matte horn buttons'],
    careInstructions: ['May bleed slightly first wash', 'Wash cold, iron hot']
  },
  {
    id: 'ls-7',
    name: 'Pondicherry Printed Resort Shirt',
    slug: 'pondicherry-printed-resort-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'half-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3899,
    compareAtPrice: 5499,
    fabric: '100% Pure Linen',
    fit: 'Relaxed',
    color: 'Linen White',
    colorHex: '#F5F1E8',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Half Sleeve',
    pattern: 'Printed',
    images: shirtImages.white,
    rating: 4.4,
    reviewCount: 19,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-08',
    description: 'Featuring a minimalist hand-stamped block print, this resort shirt celebrates artisanal Indian printing on airy pure linen fabric.',
    details: ['Artesian block print detail', 'Resort spread collar', 'Boxy relaxed fit', 'Coconut shell buttons'],
    careInstructions: ['Dry clean first time', 'Gentle hand wash inside out']
  },
  {
    id: 'ls-8',
    name: 'Cochin Check Linen Shirt',
    slug: 'cochin-check-linen-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3699,
    compareAtPrice: 4899,
    fabric: '100% Pure Linen',
    fit: 'Regular',
    color: 'Warm Beige',
    colorHex: '#C9B79C',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Checked',
    images: shirtImages.terracotta,
    rating: 4.6,
    reviewCount: 27,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-15',
    description: 'Crafted with a micro-tattersall windowpane check in neutral beige and sand tones. A clever pattern that matches light and dark trousers easily.',
    details: ['Yarn-dyed premium check pattern', 'Medium weight breathable construction', 'Premium standard spread collar', 'Double stitching details'],
    careInstructions: ['Wash in laundry bag', 'Steam press recommended']
  },
  {
    id: 'ls-9',
    name: 'Himalayan Breeze Linen Shirt',
    slug: 'himalayan-breeze-linen-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3399,
    compareAtPrice: 4599,
    fabric: '100% Pure Linen',
    fit: 'Relaxed',
    color: 'Desert Rose',
    colorHex: '#C58B82',
    sizes: SHIRT_SIZES,
    collar: 'Cutaway',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.olive,
    rating: 4.7,
    reviewCount: 52,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-04-22',
    description: 'In a soft pastel Desert Rose, this shirt evokes breezy hill afternoons. Made with a relaxed silhouette and soft collar roll.',
    details: ['Premium flax linen', 'Dusty rose colorway', 'Seamless french front placket', 'Ultra-breathable weave'],
    careInstructions: ['Gentle cycle with organic soap', 'Towel dry, warm iron']
  },
  {
    id: 'ls-10',
    name: 'Deccan Charcoal Linen Shirt',
    slug: 'deccan-charcoal-linen-shirt',
    category: 'shirts',
    subCategory: 'linen-shirts',
    collection: 'pure-linen',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_shirt',
    price: 3599,
    compareAtPrice: 4999,
    fabric: '100% Pure Linen',
    fit: 'Slim',
    color: 'Charcoal',
    colorHex: '#1F1B16',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.white,
    rating: 4.9,
    reviewCount: 61,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-03-20',
    description: 'Deep, rich Charcoal grey pure linen shirt designed for modern minimalist dressing. Perfectly fits shoulders with structured lines.',
    details: ['European linen certified quality', 'Dark charcoal mineral hue', 'Sartorial slim fit styling', 'Premium button details'],
    careInstructions: ['Wash inside out with cold water', 'Iron damp']
  },

  // ==================== COTTON LINEN SHIRTS (10 products) ====================
  {
    id: 'cls-1',
    name: 'Nilgiri Air Cotton-Linen Shirt',
    slug: 'nilgiri-air-cotton-linen-shirt',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2699,
    compareAtPrice: 3599,
    fabric: '55% Linen, 45% Organic Cotton',
    fit: 'Regular',
    color: 'Linen White',
    colorHex: '#F5F1E8',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.white,
    rating: 4.7,
    reviewCount: 142,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-01-15',
    description: 'Combining the structure and breathability of linen with the soft, wrinkle-resistant qualities of premium cotton. The ideal everyday work shirt.',
    details: ['Premium Cotton-Linen blend', 'Soft-touch brushed finish', 'Less wrinkle-prone than pure linen', 'Double stitched durability'],
    careInstructions: ['Easy machine wash cold', 'Tumble dry low', 'Iron on low heat']
  },
  {
    id: 'cls-2',
    name: 'Malabar Coastal Stripe Shirt',
    slug: 'malabar-coastal-stripe-shirt',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'half-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2899,
    compareAtPrice: 3999,
    fabric: '50% Linen, 50% Long-staple Cotton',
    fit: 'Relaxed',
    color: 'Sky Blue',
    colorHex: '#A4C3D2',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Half Sleeve',
    pattern: 'Striped',
    images: shirtImages.natural,
    rating: 4.6,
    reviewCount: 82,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-01',
    description: 'A retro striped resort shirt blending organic cotton and natural linen fibers. Featuring vertical ocean blue stripes on a soft sand background.',
    details: ['Symmetric dual-color stripes', 'Comfort relaxed fit', 'Resort camp collar style', 'Curved vintage hem'],
    careInstructions: ['Machine wash cold', 'Do not squeeze or wring']
  },
  {
    id: 'cls-3',
    name: 'Aravalli Utility Cotton-Linen Shirt',
    slug: 'aravalli-utility-cotton-linen-shirt',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2999,
    compareAtPrice: 4299,
    fabric: '60% Linen, 40% Cotton',
    fit: 'Relaxed',
    color: 'Olive Green',
    colorHex: '#5C6B4A',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.olive,
    rating: 4.8,
    reviewCount: 41,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-05-10',
    description: 'Our rugged yet sophisticated utility shirt. Built with dual chest flap pockets, epaulets, and structured cotton-linen fabric for active days.',
    details: ['Durable utility weight blend', 'Twin chest utility pockets', 'Comfortable relaxed shoulder drop', 'Premium bone-style buttons'],
    careInstructions: ['Machine wash warm', 'Iron on cotton setting']
  },
  {
    id: 'cls-4',
    name: 'Munnar Mist Mandarin Shirt',
    slug: 'munnar-mist-mandarin-shirt',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2599,
    compareAtPrice: 3499,
    fabric: '55% Linen, 45% Cotton',
    fit: 'Regular',
    color: 'Sage Grey',
    colorHex: '#8C9C8F',
    sizes: SHIRT_SIZES,
    collar: 'Mandarin',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.terracotta,
    rating: 4.4,
    reviewCount: 56,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-04-18',
    description: 'In a misty sage hue, this blended shirt offers structured comfort. The band collar gives a sleek appearance under light jackets.',
    details: ['Fine weave cotton-linen yarn', 'Soft pastel grey-green tone', 'Band collar style with single button closure', 'Slim single cuffs'],
    careInstructions: ['Machine wash, cool tumble']
  },
  {
    id: 'cls-5',
    name: 'Bengal Block Checked Blend Shirt',
    slug: 'bengal-block-checked-blend-shirt',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2799,
    compareAtPrice: 3899,
    fabric: '50% Linen, 50% Cotton',
    fit: 'Regular',
    color: 'Natural Sand',
    colorHex: '#E4D8C3',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Checked',
    images: shirtImages.white,
    rating: 4.5,
    reviewCount: 38,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-03-24',
    description: 'Featuring a bold gingham-style checkered pattern in off-white and sand tones. Keeps the wearer extremely comfortable and smart all day.',
    details: ['Classic checked weave', 'Double button barrel cuffs', 'Durable flat-felled seams', 'Superior color retention'],
    careInstructions: ['Gentle detergent, wash with like colors']
  },
  {
    id: 'cls-6',
    name: 'Coromandel Half Sleeve Printed',
    slug: 'coromandel-half-sleeve-printed',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'half-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2799,
    compareAtPrice: 3999,
    fabric: '55% Linen, 45% Cotton',
    fit: 'Relaxed',
    color: 'Desert Rose',
    colorHex: '#C58B82',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Half Sleeve',
    pattern: 'Printed',
    images: shirtImages.natural,
    rating: 4.7,
    reviewCount: 22,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-06',
    description: 'A stylish foliage micro-print on breathable linen blend. The short-sleeve styling makes it perfect for warm beach holidays.',
    details: ['Organic leafy print pattern', 'Breathable cotton blend', 'Camp-collar styled lapel', 'Relaxed square bottom hem'],
    careInstructions: ['Wash on cold, low spin']
  },
  {
    id: 'cls-7',
    name: 'Mumbai Club Slim Blend Shirt',
    slug: 'mumbai-club-slim-blend-shirt',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2899,
    compareAtPrice: 3999,
    fabric: '50% Linen, 50% Giza Cotton',
    fit: 'Slim',
    color: 'Ink Navy',
    colorHex: '#16202A',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.olive,
    rating: 4.9,
    reviewCount: 93,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-02-12',
    description: 'The deep navy color is achieved with special reactive dyes. Mixed with lustrous Giza cotton, it has a beautiful luxury finish for evening socials.',
    details: ['Premium Giza cotton blend', 'Sartorial slim fit', 'High luster luxury finish', 'Premium buttons'],
    careInstructions: ['Iron inside out with steam']
  },
  {
    id: 'cls-8',
    name: 'Thar Desert Sand Blend Shirt',
    slug: 'thar-desert-sand-blend-shirt',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2499,
    compareAtPrice: 3499,
    fabric: '60% Cotton, 40% Linen',
    fit: 'Regular',
    color: 'Warm Beige',
    colorHex: '#C9B79C',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.terracotta,
    rating: 4.5,
    reviewCount: 47,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-01',
    description: 'An approachable entry blend designed for daily wear. High organic cotton content yields exceptional softness and a highly scratch-free feel.',
    details: ['High organic cotton content', 'Scratch-free daily comfort', 'Soft collar structure', 'Chest patch pocket'],
    careInstructions: ['Tumble dry safe, iron warm']
  },
  {
    id: 'cls-9',
    name: 'Kochi Harbour Yacht Shirt',
    slug: 'kochi-harbour-yacht-shirt',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2899,
    compareAtPrice: 3999,
    fabric: '55% Linen, 45% Cotton',
    fit: 'Relaxed',
    color: 'Sky Blue',
    colorHex: '#A4C3D2',
    sizes: SHIRT_SIZES,
    collar: 'Cutaway',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.white,
    rating: 4.6,
    reviewCount: 30,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-20',
    description: 'Breezy nautical sky blue shirt crafted from our custom linen blend. Designed with a wide cutaway collar that matches shorts beautifully.',
    details: ['Breezy summer weight', 'Wide cutaway collar', 'Adjustable dual cuffs', 'Pearl buttons'],
    careInstructions: ['Dry flat, wash cold']
  },
  {
    id: 'cls-10',
    name: 'Shillong Forest Blend Shirt',
    slug: 'shillong-forest-blend-shirt',
    category: 'shirts',
    subCategory: 'cotton-linen-shirts',
    collection: 'linen-cotton-blend',
    productType: 'shirts',
    productSubType: 'full-sleeve-shirts',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_shirt',
    price: 2699,
    compareAtPrice: 3799,
    fabric: '50% Linen, 50% Cotton',
    fit: 'Slim',
    color: 'Olive Green',
    colorHex: '#5C6B4A',
    sizes: SHIRT_SIZES,
    collar: 'Spread',
    sleeve: 'Full Sleeve',
    pattern: 'Solid',
    images: shirtImages.natural,
    rating: 4.8,
    reviewCount: 51,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-03-22',
    description: 'An elegant woodland green shade shirt designed for versatile wear. The soft cotton-linen fibers draping on the skin are extremely comfortable.',
    details: ['Garment washed premium blend', 'Olive-drab luxury shade', 'Tapered slim silhouette', 'Stiff collar point stand'],
    careInstructions: ['Hand wash separately, cold water']
  },

  // ==================== LINEN PANTS (10 products) ====================
  {
    id: 'lp-1',
    name: 'Calicut Pure Linen Pants',
    slug: 'calicut-pure-linen-pants',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 3999,
    compareAtPrice: 5999,
    fabric: '100% Pure Linen',
    fit: 'Regular',
    color: 'Linen White',
    colorHex: '#F5F1E8',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.8,
    reviewCount: 105,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-02-10',
    description: 'The pinnacle of warm-weather sophistication. Features a structured waistband, belt loops, dual slash pockets, and a clean, straight-leg drape in pure flax linen.',
    details: ['100% Belgian flax linen', 'Comfort-stretch inside waist lining', 'Functional side and back welt pockets', 'YKK zip fly with button closure'],
    careInstructions: ['Dry clean or wash cold and hang dry', 'Iron while damp to release wrinkles']
  },
  {
    id: 'lp-2',
    name: 'Varanasi Drawstring Trousers',
    slug: 'varanasi-drawstring-trousers',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 3799,
    compareAtPrice: 4999,
    fabric: '100% Pure Linen',
    fit: 'Relaxed',
    color: 'Natural Sand',
    colorHex: '#E4D8C3',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.7,
    reviewCount: 120,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-03-15',
    description: 'Featuring a fully elasticated waistband and adjustable cotton drawstring, these trousers deliver ultimate lounge luxury without sacrificing elegance.',
    details: ['100% French flax linen', 'Fully elasticated waistband', 'Soft natural drawstring closure', 'Relaxed leg profile'],
    careInstructions: ['Gentle cycle wash cold', 'Iron on low setting']
  },
  {
    id: 'lp-3',
    name: 'Jaipur Summer Tailored Pants',
    slug: 'jaipur-summer-tailored-pants',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 4299,
    compareAtPrice: 5999,
    fabric: '100% Pure Linen',
    fit: 'Slim',
    color: 'Warm Beige',
    colorHex: '#C9B79C',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.natural,
    rating: 4.9,
    reviewCount: 34,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-04',
    description: 'Expertly tailored pure linen slim trousers. Built with a sharp double-pleat front and buttoned waist adjusters for custom side fittings.',
    details: ['100% Pure luxury Irish Linen', 'Pleated front tailoring', 'Adjustable side metal-buckle tabs', 'Tapered ankle finish'],
    careInstructions: ['Dry clean only', 'Hot iron with pressing cloth']
  },
  {
    id: 'lp-4',
    name: 'Kerala Breeze Linen Slacks',
    slug: 'kerala-breeze-linen-slacks',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 3899,
    compareAtPrice: 5299,
    fabric: '100% Pure Linen',
    fit: 'Regular',
    color: 'Olive Green',
    colorHex: '#5C6B4A',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.5,
    reviewCount: 42,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-18',
    description: 'Relaxed yet tailored linen slacks dyed in earthy olive. Unlined for maximum airflow during high-humidity seasons.',
    details: ['Garment-washed pure flax', 'Unlined breezy construction', 'Belt loop detailing', 'Dual rear button pockets'],
    careInstructions: ['Machine wash gentle cold', 'Hang dry in shadow']
  },
  {
    id: 'lp-5',
    name: 'Udaipur Royal Ivory Pants',
    slug: 'udaipur-royal-ivory-pants',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 4499,
    compareAtPrice: 6499,
    fabric: '100% Premium Belgian Linen',
    fit: 'Regular',
    color: 'Linen White',
    colorHex: '#F5F1E8',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.9,
    reviewCount: 50,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-04-10',
    description: 'Designed for beachside weddings and royal dinners. Heavyweight luxury linen that drapes exceptionally well and resists wrinkling better than light linen.',
    details: ['Heavy-gram Belgian linen', 'Double button-tab closure', 'Premium pocket bags', 'Full straight cut drape'],
    careInstructions: ['Dry clean highly recommended']
  },
  {
    id: 'lp-6',
    name: 'Nalanda Earth Linen Trousers',
    slug: 'nalanda-earth-linen-trousers',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 3999,
    compareAtPrice: 5499,
    fabric: '100% Pure Linen',
    fit: 'Relaxed',
    color: 'Terracotta Rust',
    colorHex: '#B85C38',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.natural,
    rating: 4.6,
    reviewCount: 18,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-09',
    description: 'Boasting a stunning rust-colored profile, these relaxed pants feature a pleated waist and slightly cropped hem for a retro resort visual aesthetic.',
    details: ['Artisanal terracotta shade', 'Double pleated front waist', 'Slightly cropped ankle hem', 'Breathable linen texture'],
    careInstructions: ['Hand wash alone, flat dry in shade']
  },
  {
    id: 'lp-7',
    name: 'Galle Resort Drawstring Pants',
    slug: 'galle-resort-drawstring-pants',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 3699,
    compareAtPrice: 4899,
    fabric: '100% Pure Linen',
    fit: 'Relaxed',
    color: 'Sky Blue',
    colorHex: '#A4C3D2',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.7,
    reviewCount: 29,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-06-01',
    description: 'Beautifully sky dyed drawstring trousers for coastal walks. Fully elasticated with deep utility side pockets for accessories.',
    details: ['Pre-washed sky blue linen', 'Soft interior cotton pocketing', 'Cotton drawstring waist', 'Relaxed leg drape'],
    careInstructions: ['Wash in cold water, hang to dry']
  },
  {
    id: 'lp-8',
    name: 'Deccan Midnight Linen Pants',
    slug: 'deccan-midnight-linen-pants',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 4199,
    compareAtPrice: 5899,
    fabric: '100% Pure Linen',
    fit: 'Slim',
    color: 'Ink Navy',
    colorHex: '#16202A',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.8,
    reviewCount: 62,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-03-29',
    description: 'Sleek, slim-cut linen pants in ink navy. Features tailored waistband and clean flat-front profile for premium evening wear.',
    details: ['Lustrous navy dyed flax', 'Flat-front minimal design', 'Tailored waistband with zip fly', 'Dual side seam pockets'],
    careInstructions: ['Wash inside out with gentle detergent']
  },
  {
    id: 'lp-9',
    name: 'Shimla Ridge Linen Chino Pants',
    slug: 'shimla-ridge-linen-chino-pants',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 4299,
    compareAtPrice: 5699,
    fabric: '100% Pure Linen',
    fit: 'Slim',
    color: 'Sage Grey',
    colorHex: '#8C9C8F',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.4,
    reviewCount: 15,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-12',
    description: 'Heavy flax construction woven in a tight diagonal twill pattern. Offers the clean look of chinos with the cool breathability of pure linen.',
    details: ['Twill woven pure linen', 'Slim-fit structured legs', 'Reinforced stitch points', 'Genuine horn buttons'],
    careInstructions: ['Dry clean or machine cold inside laundry bag']
  },
  {
    id: 'lp-10',
    name: 'Thar Rock Charcoal Pants',
    slug: 'thar-rock-charcoal-pants',
    category: 'pants',
    subCategory: 'linen-pants',
    collection: 'pure-linen',
    productType: 'trousers',
    materialType: 'pure-linen',
    tax_class: 'mens_woven_trouser',
    price: 3999,
    compareAtPrice: 5499,
    fabric: '100% Pure Linen',
    fit: 'Regular',
    color: 'Charcoal',
    colorHex: '#1F1B16',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.8,
    reviewCount: 40,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-04-05',
    description: 'An essential charcoal grey trouser that matches any pastel linen shirt in your wardrobe. Features a high waist rise and a comfortable regular-fit silhouette.',
    details: ['Organic dark charcoal hue', 'Breathable, mid-weight weave', 'High-rise structured waist', 'Dual back button tabs'],
    careInstructions: ['Iron on high heat inside out']
  },

  // ==================== COTTON LINEN PANTS (10 products) ====================
  {
    id: 'clp-1',
    name: 'Aravalli Cotton-Linen Slacks',
    slug: 'aravalli-cotton-linen-slacks',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3299,
    compareAtPrice: 4599,
    fabric: '52% Linen, 48% Premium Cotton',
    fit: 'Regular',
    color: 'Natural Sand',
    colorHex: '#E4D8C3',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.7,
    reviewCount: 115,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-01-20',
    description: 'Our top-rated everyday pants. Combining the cooling luxury of French linen with the day-long softness and shape retention of organic cotton.',
    details: ['Airy cotton-linen fabric', 'Flat-front mid-rise waist', 'Reinforced bar-tacks at pocket edges', 'Premium horn buttons'],
    careInstructions: ['Easy machine wash cold', 'Iron at moderate settings']
  },
  {
    id: 'clp-2',
    name: 'Shimla Textured Knit Trousers',
    slug: 'shimla-textured-knit-trousers',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3499,
    compareAtPrice: 4999,
    fabric: '55% Cotton, 45% Linen',
    fit: 'Relaxed',
    color: 'Warm Beige',
    colorHex: '#C9B79C',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.natural,
    rating: 4.6,
    reviewCount: 78,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-03',
    description: 'Woven with a micro-houndstooth texture, these lightweight trousers provide an elegant surface detail that hides wrinkles beautifully.',
    details: ['Textured houndstooth knit weave', 'Relaxed leg tapering', 'Comfort-stretch elastic insert in back', 'Button loop pockets'],
    careInstructions: ['Do not tumble dry', 'Lay flat to dry']
  },
  {
    id: 'clp-3',
    name: 'Nilgiri Breeze Slim Pants',
    slug: 'nilgiri-breeze-slim-pants',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3199,
    compareAtPrice: 4299,
    fabric: '50% Linen, 50% Organic Cotton',
    fit: 'Slim',
    color: 'Linen White',
    colorHex: '#F5F1E8',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.8,
    reviewCount: 65,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-02-28',
    description: 'The clean profile of white trousers without the high maintenance. The dense cotton-linen weave ensures opacity and exceptional softness.',
    details: ['Thick, opaque cotton-linen blend', 'Tailored slim silhouette', 'Double waistband button hook', 'Premium satin inside seams'],
    careInstructions: ['Wash with white clothing only', 'Bleach-free detergent']
  },
  {
    id: 'clp-4',
    name: 'Kodaikanal Forest Slacks',
    slug: 'kodaikanal-forest-slacks',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3399,
    compareAtPrice: 4699,
    fabric: '55% Linen, 45% Cotton',
    fit: 'Regular',
    color: 'Olive Green',
    colorHex: '#5C6B4A',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.5,
    reviewCount: 39,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-22',
    description: 'Deep forest green trousers engineered for everyday ease. Ideal for transition wear from air-conditioned offices to tropical evenings.',
    details: ['Mid-weight linen cotton blend', 'Sophisticated olive shade', 'Wrinkle-resistant weaving', 'Angled front pocket entries'],
    careInstructions: ['Wash cold, tumble dry low']
  },
  {
    id: 'clp-5',
    name: 'Chambal Safari Drawstring Slacks',
    slug: 'chambal-safari-drawstring-slacks',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3299,
    compareAtPrice: 4499,
    fabric: '60% Cotton, 40% Linen',
    fit: 'Relaxed',
    color: 'Warm Beige',
    colorHex: '#C9B79C',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.natural,
    rating: 4.6,
    reviewCount: 33,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-06-10',
    description: 'Designed with a relaxed drawstring utility style, these hybrid trousers offer superior comfort for weekend escapes and general lounging.',
    details: ['Cotton-dominant blend for soft skin contact', 'Drawstring waist + belt loops', 'Triple stitched seams for durability', 'Elastic side expansion'],
    careInstructions: ['Machine wash, tumble dry low']
  },
  {
    id: 'clp-6',
    name: 'Mysore Royal Navy Slacks',
    slug: 'mysore-royal-navy-slacks',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3499,
    compareAtPrice: 4799,
    fabric: '50% Linen, 50% Luxury Cotton',
    fit: 'Slim',
    color: 'Ink Navy',
    colorHex: '#16202A',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.9,
    reviewCount: 71,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-03-12',
    description: 'Sophisticated dark navy pants featuring an integrated stretch-band waistband. Pairs beautifully with light-colored linen shirts.',
    details: ['Lustrous navy blend fabric', 'Stretch elastic insert inside waist', 'Slim modern leg drape', 'Contrast lining inside pockets'],
    careInstructions: ['Dry clean recommended', 'Steam iron on reverse']
  },
  {
    id: 'clp-7',
    name: 'Darjeeling Autumn Slacks',
    slug: 'darjeeling-autumn-slacks',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3399,
    compareAtPrice: 4599,
    fabric: '55% Linen, 45% Cotton',
    fit: 'Regular',
    color: 'Terracotta Rust',
    colorHex: '#B85C38',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.natural,
    rating: 4.7,
    reviewCount: 20,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-08',
    description: 'Warm rust colored slacks crafted from a soft combed cotton and organic flax blend. The color stays rich and bright even after multiple washes.',
    details: ['Rich terracotta colorway', 'Combed cotton blending', 'Regular straight drape', 'Button flap back pockets'],
    careInstructions: ['Wash in cold water, hang dry']
  },
  {
    id: 'clp-8',
    name: 'Coorg Meadow Green Pants',
    slug: 'coorg-meadow-green-pants',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3199,
    compareAtPrice: 4299,
    fabric: '50% Linen, 50% Cotton',
    fit: 'Slim',
    color: 'Sage Grey',
    colorHex: '#8C9C8F',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.3,
    reviewCount: 24,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-02',
    description: 'A pale moss-green shade that acts as an excellent neutral tone. Tailored with a modern slim profile and slanted waist pockets.',
    details: ['Lightweight slub texture', 'Pale sage moss shade', 'Double-button secure tab', 'YKK metal zipper'],
    careInstructions: ['Machine wash cold, iron warm']
  },
  {
    id: 'clp-9',
    name: 'Malabar Mist Ivory Pants',
    slug: 'malabar-mist-ivory-pants',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3299,
    compareAtPrice: 4499,
    fabric: '55% Organic Cotton, 45% Linen',
    fit: 'Relaxed',
    color: 'Linen White',
    colorHex: '#F5F1E8',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.7,
    reviewCount: 55,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-04-12',
    description: 'Our most relaxed blend trouser yet. Offering incredible ease around thighs and knees while preserving a clean, smart-casual beach profile.',
    details: ['Extra soft linen-cotton blend', 'Relaxed-fit wide thighs', 'Drawstring interior waistband option', 'Slash pocket details'],
    careInstructions: ['Gentle cycle cold, do not tumble dry']
  },
  {
    id: 'clp-10',
    name: 'Mumbai Club Charcoal Pants',
    slug: 'mumbai-club-charcoal-pants',
    category: 'pants',
    subCategory: 'cotton-linen-pants',
    collection: 'linen-cotton-blend',
    productType: 'trousers',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_woven_trouser',
    price: 3499,
    compareAtPrice: 4899,
    fabric: '50% Linen, 50% Organic Cotton',
    fit: 'Regular',
    color: 'Charcoal',
    colorHex: '#1F1B16',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.8,
    reviewCount: 43,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-03-20',
    description: 'Deep charcoal grey slacks combining high organic cotton elasticity with structured linen weave lines. Excellent drape and comfort.',
    details: ['Organic charcoal dyed', 'Perfect balance of structure and softness', 'Tailored back welt pockets', 'Luxe metal belt-bar hook'],
    careInstructions: ['Wash alone first, iron inside out']
  },

  // ==================== CHINOS (10 products) ====================
  {
    id: 'ch-1',
    name: 'Bengal Premium Chinos',
    slug: 'bengal-premium-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3499,
    compareAtPrice: 4999,
    fabric: '70% Cotton Twill, 30% Linen',
    fit: 'Slim',
    color: 'Natural Sand',
    colorHex: '#E4D8C3',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.9,
    reviewCount: 165,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-01-10',
    description: 'Our flagship chino. Woven in a durable heavyweight twill with high-grade organic cotton and long-staple linen for unmatched comfort and daily performance.',
    details: ['Heavyweight cotton-linen twill', 'Sleek slim fit', 'Satin-finished interior seams', 'Button-through back welt pockets'],
    careInstructions: ['Machine wash warm', 'Tumble dry low', 'Iron on medium-high']
  },
  {
    id: 'ch-2',
    name: 'Punjab Indigo Twill Chinos',
    slug: 'punjab-indigo-twill-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3299,
    compareAtPrice: 4499,
    fabric: '65% Cotton, 35% Linen Twill',
    fit: 'Regular',
    color: 'Ink Navy',
    colorHex: '#16202A',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.7,
    reviewCount: 108,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-03-05',
    description: 'The deep, clean navy wash provides the classic appearance of chinos while the linen fibers keep your skin cool and dry throughout the day.',
    details: ['Durable twill weave', 'Refined regular fit', 'Clean coin pocket detailing', 'Genuine dark horn button closures'],
    careInstructions: ['Wash inside out cold', 'Do not bleach']
  },
  {
    id: 'ch-3',
    name: 'Desert Dunes Khaki Chinos',
    slug: 'desert-dunes-khaki-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3399,
    compareAtPrice: 4699,
    fabric: '70% Combed Cotton, 30% Linen',
    fit: 'Slim',
    color: 'Warm Beige',
    colorHex: '#C9B79C',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.natural,
    rating: 4.6,
    reviewCount: 89,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-14',
    description: 'The definitive khaki shade. Designed with a clean flat-front aesthetic and tapered lower leg that rests elegantly on loafers.',
    details: ['Definitive khaki mineral tone', 'Premium combed cotton blend', 'Tailored waist rise', 'Double bar-tacked pockets'],
    careInstructions: ['Wash with like colors', 'Steam press recommended']
  },
  {
    id: 'ch-4',
    name: 'Gwalior Forest Twill Chinos',
    slug: 'gwalior-forest-twill-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3499,
    compareAtPrice: 4899,
    fabric: '68% Cotton, 32% Linen Twill',
    fit: 'Regular',
    color: 'Olive Green',
    colorHex: '#5C6B4A',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.8,
    reviewCount: 52,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-04-12',
    description: 'A deep olive-drab hue designed for modern utility aesthetics. Built with a robust twill weave that resists abrasions and stays structured.',
    details: ['Durable military-grade weave', 'Premium olive-drab hue', 'Regular-rise straight drape', 'Thick belt loop bars'],
    careInstructions: ['Wash warm inside laundry bags']
  },
  {
    id: 'ch-5',
    name: 'Thar Stone Charcoal Chinos',
    slug: 'thar-stone-charcoal-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3599,
    compareAtPrice: 4999,
    fabric: '70% Cotton, 30% Linen Twill',
    fit: 'Slim',
    color: 'Charcoal',
    colorHex: '#1F1B16',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.8,
    reviewCount: 77,
    bestseller: true,
    newArrival: false,
    dateAdded: '2026-02-15',
    description: 'A dark coal shade chino. An exceptional alternative to denim or black jeans, offering deep breathability and supreme structure.',
    details: ['Carbon dark mineral hue', 'Fine diagonal twill texture', 'Tailored slim styling', 'Silver-grade metal hook clasp'],
    careInstructions: ['Wash inside out, do not dry in direct sun']
  },
  {
    id: 'ch-6',
    name: 'Delhi Classic Bone Chinos',
    slug: 'delhi-classic-bone-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3499,
    compareAtPrice: 4899,
    fabric: '75% Combed Cotton, 25% Linen Twill',
    fit: 'Regular',
    color: 'Linen White',
    colorHex: '#F5F1E8',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.5,
    reviewCount: 46,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-19',
    description: 'An elegant bone-white colored chino trousers designed for classic sartorial pairings. Beautifully resists wrinkles due to combed cotton dominant fibers.',
    details: ['Bone ivory colored twill', 'Combed cotton comfort', 'Straight-leg regular silhouette', 'Dual front coin-slash pockets'],
    careInstructions: ['Machine wash cold, lay flat to dry']
  },
  {
    id: 'ch-7',
    name: 'Himalayan Ridge Sage Chinos',
    slug: 'himalayan-ridge-sage-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3599,
    compareAtPrice: 4999,
    fabric: '70% Cotton, 30% Linen Twill',
    fit: 'Slim',
    color: 'Sage Grey',
    colorHex: '#8C9C8F',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.dark,
    rating: 4.6,
    reviewCount: 31,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-07',
    description: 'Dyed in a beautiful neutral Sage Grey tone. Woven in fine luxury twill for active office meetings and weekend travels.',
    details: ['Sage grey twill weave', 'Stretchable cotton core blend', 'Slim silhouette tapering', 'Dual rear button tabs'],
    careInstructions: ['Gentle cycle with like colors']
  },
  {
    id: 'ch-8',
    name: 'Aravalli Brick Clay Chinos',
    slug: 'aravalli-brick-clay-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3699,
    compareAtPrice: 5199,
    fabric: '68% Cotton, 32% Linen Twill',
    fit: 'Regular',
    color: 'Terracotta Rust',
    colorHex: '#B85C38',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.natural,
    rating: 4.7,
    reviewCount: 23,
    bestseller: false,
    newArrival: true,
    dateAdded: '2026-07-12',
    description: 'A striking Terracotta-Rust colored chino for bold sartorial wear. The luxury blend is incredibly soft on the skin and keeps the thighs comfortable.',
    details: ['Terracotta rich dye', 'Regular cut comfort trousers', 'Heavy duty copper buttons', 'High density weave'],
    careInstructions: ['Wash separately first, iron inside out']
  },
  {
    id: 'ch-9',
    name: 'Deccan Indigo Sky Chinos',
    slug: 'deccan-indigo-sky-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3399,
    compareAtPrice: 4599,
    fabric: '70% Cotton, 30% Linen Twill',
    fit: 'Slim',
    color: 'Sky Blue',
    colorHex: '#A4C3D2',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.4,
    reviewCount: 19,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-06-02',
    description: 'A vibrant sky-blue chino designed for maritime outings and poolside drinks. Extremely lightweight, soft, and easy to roll up at cuffs.',
    details: ['Vibrant sky blue twill', 'Ultra-light summer weight', 'Easily rollable cuffs', 'Contrast button threads'],
    careInstructions: ['Wash warm, do not twist']
  },
  {
    id: 'ch-10',
    name: 'Thar Dune Rose Chinos',
    slug: 'thar-dune-rose-chinos',
    category: 'pants',
    subCategory: 'chinos',
    collection: 'chinos',
    productType: 'chinos',
    materialType: 'linen-cotton-blend',
    tax_class: 'mens_chino',
    price: 3499,
    compareAtPrice: 4799,
    fabric: '72% Cotton, 28% Linen Twill',
    fit: 'Relaxed',
    color: 'Desert Rose',
    colorHex: '#C58B82',
    sizes: PANTS_SIZES,
    pattern: 'Solid',
    images: pantImages.light,
    rating: 4.8,
    reviewCount: 14,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-25',
    description: 'An elegant vintage rose hue chino crafted in a relaxed fit. Keeps the wearer feeling comfortable yet sophisticated all afternoon.',
    details: ['Vintage desert rose colorway', 'Comfortable relaxed fit', 'Durable pocket linings', 'YKK metal secure zipper'],
    careInstructions: ['Machine wash cool, low dryer settings']
  },

  // ==================== POLOS (10 products) ====================
  {
    id: 'po-1',
    name: 'Mahabaleshwar Linen Knit Polo',
    slug: 'mahabaleshwar-linen-knit-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2499,
    compareAtPrice: 3499,
    fabric: '60% Linen, 40% Organic Cotton',
    fit: 'Regular',
    color: 'Natural Sand',
    colorHex: '#E4D8C3',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.natural,
    rating: 4.7,
    reviewCount: 145,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-01-22',
    description: 'Knit from a custom luxurious linen-cotton blend yarn. It features an open knit structure for premium ventilation, a ribbed polo collar, and a buttonless placket for a vintage look.',
    details: ['Linen-cotton luxury blend knit', 'Sophisticated buttonless collar placket', 'Breathable open-knit mesh texture', 'Ribbed cuffs and bottom hem'],
    careInstructions: ['Hand wash or use delicate wool wash cycle', 'Dry flat on towel', 'Do not hang dry']
  },
  {
    id: 'po-2',
    name: 'Udaipur Textured Polo',
    slug: 'udaipur-textured-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2699,
    compareAtPrice: 3899,
    fabric: '55% Linen, 45% Combed Cotton',
    fit: 'Slim',
    color: 'Linen White',
    colorHex: '#F5F1E8',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.white,
    rating: 4.9,
    reviewCount: 84,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-03-12',
    description: 'Featuring a sleek three-button closure and ribbed collar, this classic white polo combines the crispness of fine linen with the plush softness of combed cotton.',
    details: ['Premium structured knit', '3-button traditional placket', 'Embroidered tone-on-tone Kora logo', 'Ventilated mesh underarms'],
    careInstructions: ['Wash inside out on cold', 'Tumble dry low']
  },
  {
    id: 'po-3',
    name: 'Kovalam Navy Club Polo',
    slug: 'kovalam-navy-club-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2799,
    compareAtPrice: 3999,
    fabric: '50% Linen, 50% Giza Cotton Knit',
    fit: 'Slim',
    color: 'Ink Navy',
    colorHex: '#16202A',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.terracotta,
    rating: 4.8,
    reviewCount: 112,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-02-18',
    description: 'Lustrous, deep navy blue knit polo shirt designed for premium beach clubs and afternoon golf. Maintains custom tailored fit contours.',
    details: ['Luxury Giza Cotton and Linen knit', 'Tailored slim silhouette', 'High luster navy colorway', 'Matte black natural buttons'],
    careInstructions: ['Wash separately first', 'Warm iron inside out']
  },
  {
    id: 'po-4',
    name: 'Ooty Fern Green Polo',
    slug: 'ooty-fern-green-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2599,
    compareAtPrice: 3499,
    fabric: '55% Linen, 45% Organic Cotton',
    fit: 'Regular',
    color: 'Olive Green',
    colorHex: '#5C6B4A',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.olive,
    rating: 4.6,
    reviewCount: 54,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-15',
    description: 'An elegant fern green polo designed for premium comfort. Features comfortable ribbed details and a classic buttoned neck look.',
    details: ['Certified organic organic cotton blend', 'Durable ribbed neck stand', 'Regular-fit ease', 'Two button styling'],
    careInstructions: ['Machine wash cold, low speed spin']
  },
  {
    id: 'po-5',
    name: 'Goa Coast Striped Polo',
    slug: 'goa-coast-striped-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2899,
    compareAtPrice: 4199,
    fabric: '60% Linen, 40% Cotton Knit',
    fit: 'Relaxed',
    color: 'Sky Blue',
    colorHex: '#A4C3D2',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Striped',
    images: shirtImages.natural,
    rating: 4.5,
    reviewCount: 30,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-07-05',
    description: 'A stylish horizontal striped knit polo evoking warm ocean breezes. Constructed with vintage ivory-colored stripes against sky blue knit.',
    details: ['Horizontal stripe knit texture', 'Vintage open collar styling', 'Comfortable relaxed cuffs', 'Contrast button details'],
    careInstructions: ['Dry flat, gentle hand wash alone']
  },
  {
    id: 'po-6',
    name: 'Deccan Charcoal Knit Polo',
    slug: 'deccan-charcoal-knit-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2699,
    compareAtPrice: 3899,
    fabric: '50% Linen, 50% Cotton Knit',
    fit: 'Slim',
    color: 'Charcoal',
    colorHex: '#1F1B16',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.white,
    rating: 4.8,
    reviewCount: 66,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-04-12',
    description: 'A deep grey charcoal knit polo. Works as an exceptional sleek layering piece under linen suits or tailored blazer jackets.',
    details: ['Dark charcoal mineral hue knit', 'Sartorial slim contouring', 'Soft knit breathable fabric', 'Mother of pearl secure buttons'],
    careInstructions: ['Dry clean or delicate wash cold']
  },
  {
    id: 'po-7',
    name: 'Jaipur Dusk Polo',
    slug: 'jaipur-dusk-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2799,
    compareAtPrice: 3999,
    fabric: '55% Linen, 45% Organic Cotton',
    fit: 'Regular',
    color: 'Terracotta Rust',
    colorHex: '#B85C38',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.terracotta,
    rating: 4.7,
    reviewCount: 19,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-07-11',
    description: 'An earth-toned Terracotta rust knit polo. Adds a rich splash of color while maintaining standard breathable resort-wear elegance.',
    details: ['Fine-knit organic cotton-linen', 'Clay terracotta colorway', 'Regular fit style', 'Elegant open rib-placket'],
    careInstructions: ['Wash cold inside out, lay flat']
  },
  {
    id: 'po-8',
    name: 'Shimla Ridge Sage Polo',
    slug: 'shimla-ridge-sage-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2699,
    compareAtPrice: 3799,
    fabric: '50% Linen, 50% Cotton Knit',
    fit: 'Slim',
    color: 'Sage Grey',
    colorHex: '#8C9C8F',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.olive,
    rating: 4.4,
    reviewCount: 25,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-05-05',
    description: 'Pale sage grey-green knit polo crafted from premium slub yarns. Highly breathable and sits extremely soft on shoulders.',
    details: ['Slub texture organic knit', 'Pale sage moss hue', 'Slim fit contour styling', 'Coconut shell button look'],
    careInstructions: ['Delicate wash, iron flat']
  },
  {
    id: 'po-9',
    name: 'Cochin Sand Dunes Polo',
    slug: 'cochin-sand-dunes-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2499,
    compareAtPrice: 3499,
    fabric: '55% Combed Cotton, 45% Linen',
    fit: 'Regular',
    color: 'Warm Beige',
    colorHex: '#C9B79C',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.white,
    rating: 4.6,
    reviewCount: 41,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-04-18',
    description: 'A classic beige polo featuring dual-color contrast piping on cuffs and collar edge. Adds a preppy touch to resort relaxed pants.',
    details: ['Fine-knit combed cotton blend', 'Sand beige base with cream piping', 'Comfortable stretch knit', 'Three button secure neck'],
    careInstructions: ['Wash in laundry bag cold']
  },
  {
    id: 'po-10',
    name: 'Munnar Rose Garden Polo',
    slug: 'munnar-rose-garden-polo',
    category: 'polos',
    subCategory: 'polos',
    status: 'archived',
    isDecommissioned: true,
    price: 2799,
    compareAtPrice: 3999,
    fabric: '50% Linen, 50% Organic Cotton Knit',
    fit: 'Relaxed',
    color: 'Desert Rose',
    colorHex: '#C58B82',
    sizes: SHIRT_SIZES,
    collar: 'Polo Collar',
    sleeve: 'Half Sleeve',
    pattern: 'Solid',
    images: shirtImages.terracotta,
    rating: 4.5,
    reviewCount: 11,
    bestseller: false,
    newArrival: false,
    dateAdded: '2026-07-13',
    description: 'A luxurious dusty rose knit polo shirt with an active resort feel. Features a relaxed body drape and extra stretchy neck openings.',
    details: ['Premium organic cotton-linen', 'Relaxed silhouette fitting', 'Lightweight summer knit', 'Premium tone buttons'],
    careInstructions: ['Machine wash cold, dry flat']
  }
];

export const mockReviews: Review[] = [
  { id: 'rev-1', userName: 'Aman S.', rating: 5, date: '2026-06-15', comment: 'Absolutely the best linen shirts I have ever owned. The Amalfi Linen in White feels incredibly luxurious, fits perfectly in Regular, and breathes so well in Mumbai heat.', verified: true },
  { id: 'rev-2', userName: 'Rohan M.', rating: 5, date: '2026-06-28', comment: 'Purchased 2 Calicut Pants and 3 Goa Shirts. The quality of fabric and tailored stitching is top-notch. Love the subtle brand look.', verified: true },
  { id: 'rev-3', userName: 'Vikram K.', rating: 4, date: '2026-07-02', comment: 'Very comfortable but linen does wrinkle as expected. The cotton-linen shirts stay a bit crisper. Will buy again!', verified: true },
  { id: 'rev-4', userName: 'Kabir B.', rating: 5, date: '2026-07-10', comment: 'The Bengal Chinos are an absolute game changer! Incredible structure, fits slim but breathes like pure air. Terrific!', verified: true }
];

export const categoryFAQs = {
  shirts: [
    { q: 'How do I care for my Kora pure linen shirts?', a: 'We recommend gentle hand wash or machine wash on a cold cycle with mild detergent. Hang dry in shade. To get a crisp look, iron while the fabric is slightly damp, or use high steam.' },
    { q: 'What is the difference between Pure Linen and Cotton Linen?', a: 'Pure Linen is made from 100% Belgian flax, offering the maximum possible breathability and a distinct textured drape. Our Cotton-Linen blends combine flax with organic cotton, which results in a softer, heavier feel that wrinkles less and is easier to iron.' },
    { q: 'Do these shirts shrink after washing?', a: 'All our fabrics are pre-washed and pre-shrunk during our finishing process. Standard washing will not cause noticeable shrinkage, provided you avoid hot water and hot tumble dryers.' },
    { q: 'Which fits do you offer?', a: 'We offer Slim Fit (tapered waist and snug shoulders), Regular Fit (classic structured look with comfortable ease), and Relaxed Fit (roomy chest, shoulders, and curved hem for an airy beach drape).' }
  ],
  pants: [
    { q: 'Do the pants come with an adjustable waistband?', a: 'Yes! Many of our pants feature built-in comfort details. Our Varanasi Drawstrings have fully elastic waistbands, while our tailored Jaipur Trousers feature luxury side adjusters with metal buckles, and our slacks have a subtle flex-lining.' },
    { q: 'How long are the trouser lengths?', a: 'Our pants are tailored to standard ankle-length rises, designed to rest elegantly right above your shoes or loafers without pooling. Refer to our size guide for precise inseam measurements.' },
    { q: 'Are white linen pants transparent?', a: 'We use a premium, higher-weight double-twisted yarn for our Linen White pants (e.g. Udaipur and Calicut) to ensure excellent opacity while preserving high ventilation.' },
    { q: 'Can I wash my linen chinos in a machine?', a: 'Yes, our Chinos are crafted from a robust twill weave of organic cotton and linen, which makes them extremely durable and perfectly safe for standard machine washing on warm/cold.' }
  ],
  polos: [
    { q: 'Are these polos woven or knit?', a: 'Our polos are fine-knit from premium blended slub yarns, giving them a beautiful open-knit mesh texture that is much softer and stretchier than standard woven shirts.' },
    { q: 'How do I wash a knit linen polo without stretching it?', a: 'Knitwear should be washed gently on cold and always dried flat on a clean towel. Never hang knit polos while wet, as the gravity weight of water can stretch out the shoulders and hem.' }
  ]
};

export const seoContent = {
  'linen-shirts': {
    title: 'Pure Premium Linen Shirts for Men',
    description: 'Explore Sa and Sha’s signature selection of pure, lightweight linen shirts. Tailored from premium European flax, our solid, striped, and Mandarin collar shirts deliver ultimate ventilation, moisture-wicking ease, and a timeless, sophisticated aesthetic for the modern gentleman.',
    comparisonTitle: 'Pure Linen vs. Standard Cotton Shirts',
    comparisonText: 'While cotton shirts offer basic softness, pure linen shirts possess hollow flax fibers that conduct air and humidity away from the skin at twice the rate. Linen is also naturally hypoallergenic, three times stronger than cotton, and gains a luxurious character with every wash.'
  },
  'cotton-linen-shirts': {
    title: 'Easy-Care Cotton Linen Blend Shirts',
    description: 'Get the breezy look of linen with the structured softness of long-staple cotton. Sa and Sha’s blended shirts offer superior wrinkle resistance, high durability, and a smooth, scratch-free texture that holds its crisp drape through active days at work or leisure.',
    comparisonTitle: 'Why Choose Cotton-Linen Blends?',
    comparisonText: 'Ideal for daily workwear, cotton-linen blends provide a smart, professional aesthetic with minimal ironing. You get 50% more wrinkle resistance compared to pure linen while maintaining excellent thermal regulation.'
  },
  'linen-pants': {
    title: 'Tailored Men’s Pure Linen Trousers & Drawstrings',
    description: 'Redefine hot-weather styling with Kora’s pure linen trousers. From tailored pleated trousers with metal side adjusters to relaxed drawstring lounge pants, our pure flax legwear keeps you poised, cool, and comfortable in any setting.',
    comparisonTitle: 'Drawstring vs. Tailored Linen Trousers',
    comparisonText: 'Our drawstring linen trousers feature elastic waistbands designed for casual luxury, holiday resorts, and lazy afternoons. Our tailored trousers feature clean flat-fronts, side buckle tabs, and regular cuffs perfect for summer weddings and semi-formal soirées.'
  },
  'cotton-linen-pants': {
    title: 'Comfortable Cotton-Linen Casual Trousers',
    description: 'Everyday trousers engineered for lightweight, durable comfort. Blending pure linen threads with combed organic cotton yields exceptionally soft slacks that stay smooth and crisp, perfect for smart-casual styling.',
    comparisonTitle: 'What makes Kora Blends unique?',
    comparisonText: 'We double-spin our combed organic cotton with European flax, producing a fabric that feels cooling on the skin, blocks UV rays, and retains its structured leg profile even after a long flight.'
  },
  'chinos': {
    title: 'Premium Linen-Twill Chino Pants for Men',
    description: 'A classic wardrobe staple, upgraded. Sa and Sha’s premium chinos are woven from heavy twill combining high-grade cotton with structured linen. Featuring a clean flat-front, coin pockets, and tailored fits for active, polished wear.',
    comparisonTitle: 'Chinos vs. Linen Pants',
    comparisonText: 'Traditional chinos are 100% thick cotton, which can trap heat. Kora’s Linen-Cotton Chinos provide the robust weight, thickness, and structure of regular chinos, but the 30% linen integration allows heat to escape, creating a breezy dry wearing experience.'
  },
  'polos': {
    title: 'Luxurious Knit Linen Polos',
    description: 'Elevate your off-duty attire with Sa and Sha’s hand-knit polos. Woven from rich blended flax yarns, our open-mesh polos offer exceptional natural stretch, classic collars, and elegant buttonless plackets for a touch of vintage mid-century style.',
    comparisonTitle: 'Linen knit polos vs. Pique Cotton polos',
    comparisonText: 'Standard pique cotton polos are heavy and hold sweat. Our knit linen-blend polos are lightweight, naturally anti-odor, and feature a unique ventilated mesh texture that actively drops skin temperature.'
  }
};
